### ISSUE TITLE
Write setup

### ISSUE THREAD

**Issue by kashalls** [luizweb/ARGB-ESP32#1]
Hi there!

I'm interested in your project, I was looking for a way to use an ESP to controll ARGB. Is there any chance you can explain how you have this setup?

Thanks!

**Comment by luizweb** [comment]
Sure ! it's actually quite simple, here's a picture of the board:

<img src="https://i.imgur.com/22nJVGm.jpg?1" alt="esp32"/>

The setup is just a ESP32 with a DC plug and a output for the argb strip (data, 5v, ground)
it runs on a 5v 5a power supply (you will most likely have problems if you use one with less than 5a)

Since the argb strip and the ESP32 both runs on 5v, you wont need any kind of buck converter
so the setup is pretty much this

**Comment by kashalls** [comment]
How do you think this would handle controlling 3pin 5v RGB fans in a computer case? I wanted some special functions that I would add that a controller wouldn't be able to add.

**Comment by luizweb** [comment]
I guess it's exactly the same scenario as I am using it, the difference is that I am using it on a argb led strip ws2812b, and not a rgb fan, so you have to account for how many LEDs you have and put that on the variable

Also keep in mind that the script is very crude, its only a on/off switch with a single rainbow effect, but I will improve the web app and add more effects once I have some time

**Comment by luizweb** [comment]
Overall, the script is just a multitasking solution for running a web server and ARGB effects at the same time on the same board.
